POST http://localhost:5000/api/books
Content-Type: application/json

{
    "booktitle": "hello father",
    "bookname": "how is your dather",
    "bookBody": "its a bad sweet day"
}

###

GET http://localhost:5000/api/books

###

DELETE http://localhost:5000/api/books/63961707a175023b08e3f870